apiVersion: v1
kind: Service
metadata:
  name: kubeproyectofinal010723
spec:
  selector:
    app: kubeproyectofinal010723
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeproyectofinal010723
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeproyectofinal010723
  template:
    metadata:
      labels:
        app: kubeproyectofinal010723
    spec:
      containers:
        - name: kubecontainerproyectofinal010723
          image: jpesquivel/proyectofinal010723:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://jppe:pepe001@coderexample.sfwkefl.mongodb.net/ecommerce?retryWrites=true&w=majority
          imagePullPolicy: Always
